-- -- Seed an initial admin user to bootstrap:
-- INSERT INTO gql_cms.users (email, auth_provider, full_name) VALUES ('admin@example.com','local','Admin') RETURNING id;
-- -- Assign admin role
-- INSERT INTO gql_cms.user_roles(user_id, role_name)
-- VALUES ((SELECT id FROM gql_cms.users WHERE email = 'admin@example.com'),'admin');
--
-- INSERT INTO gql_cms.user_acl(target_user_id, user_id, role_name)
--   VALUES ((SELECT id FROM gql_cms.users WHERE email = 'admin@example.com'), (SELECT id FROM gql_cms.users WHERE email = 'admin@example.com'), 'owner');

-- Seed manager user for analytics access is now done in 91-northwind-auth-seed.sql
-- This file is kept minimal to avoid dependency issues with ACL schema
