export const i18n={
    en: { langName:'English US'     , flag:'us' , welcome  : "Welcome to admin-ui"                      , dashboardContent: "This is your dashboard content."               , home: 'Home'        , users: 'Users'        , urls: 'URLs'        , stats: 'Stats'        , about: 'About' },
    'en-gb': { langName:'English GB', flag:'gb' , welcome  : "Great to have you with us at admin-ui"    , dashboardContent: "This is your dashboard content."               , home: 'Home'        , users: 'Users'        , urls: 'URLs'        , stats: 'Stats'        , about: 'About' },
    es: { langName:'Español'        , flag:'es' , welcome  : "Bienvenido a admin-ui"                    , dashboardContent: "Este es el contenido de tu panel."             , home: 'Inicio'      , users: 'Usuarios'     , urls: 'URLs'        , stats: 'Estadísticas' , about: 'Acerca de' },
    fr: { langName:'Français'       , flag:'fr' , welcome  : "Bienvenue sur admin-ui"                   , dashboardContent: "Ceci est le contenu de votre tableau de bord." , home: 'Accueil'     , users: 'Utilisateurs' , urls: 'URLs'        , stats: 'Statistiques' , about: 'À propos' },
    de: { langName:'Deutsch'        , flag:'de' , welcome  : "Willkommen bei admin-ui"                  , dashboardContent: "Dies ist Ihr Dashboard-Inhalt."                , home: 'Startseite'  , users: 'Benutzer'     , urls: 'URLs'        , stats: 'Statistiken'  , about: 'Über' },
    jp: { langName:'日本語'          , flag:'jp' , welcome  : "admin-uiへようこそ"                         , dashboardContent: "これはあなたのダッシュボードの内容です。"              , home: 'ホーム'       , users: 'ユーザー'       , urls: 'URL'         , stats: '統計'          , about: 'について' },
    pt: { langName:'Português'      , flag:'pt' , welcome  : "Bem-vindo ao admin-ui"                    , dashboardContent: "Este é o conteúdo do seu painel."              , home: 'Início'      , users: 'Usuários'     , urls: 'URLs'        , stats: 'Estatísticas' , about: 'Sobre' },
    il: { langName:'עברית'          , flag:'il'  , welcome : "ברוכים הבאים ל-admin-ui"                   , dashboardContent: "זהו תוכן לוח הבקרה שלך."                        , home: 'בית'         , users: 'משתמשים'      , urls: 'קישורים'     , stats: 'סטטיסטיקות'   , about: 'על אודות' },
    in: { langName:'हिन्दी'            , flag:'in' , welcome : "admin-ui में आपका स्वागत है"                   , dashboardContent: "यह आपका डैशबोर्ड सामग्री है।"                         , home: 'मुखपृष्ठ'        , users: 'उपयोगकर्ता'     , urls: 'यूआरएल'       , stats: 'आंकड़े'         , about: 'परिचय' },
    ua: { langName:'Українська'     , flag:'ua' , welcome : "Ласкаво просимо до admin-ui"               , dashboardContent: "Це вміст вашої інформаційної панелі."          , home: 'Головна'     , users: 'Користувачі'  , urls: 'URL-адреси'  , stats: 'Статистика'   , about: 'Про нас' },
    kr: { langName:'한국어'          , flag:'kr' , welcome : "admin-ui에 오신 것을 환영합니다"               , dashboardContent: "이것은 귀하의 대시보드 콘텐츠입니다."                , home: '홈'           , users: '사용자'        , urls: 'URL'         , stats: '통계'          , about: '소개' },
    ar: { langName:'العربية'        , flag:'sa' , welcome : "مرحبًا بك في admin-ui"                       , dashboardContent: "هذا هو محتوى لوحة التحكم الخاصة بك."            , home: 'الرئيسية'     , users: 'المستخدمون'   , urls: 'الروابط'     , stats: 'الإحصائيات'   , about: 'حول' },
};